import NavHome from "./NavHome";
import Hero from "./Hero";
import Button from "./Button";
import Download from "./Download";
import Demo from "./Demo";
import InputText from "./InputText";
import About from "./About";
import Card from "./Card";
import Footer from "./Footer";
import NavProfile from "./NavProfile";
import ContentRegis from "./ContentRegis";
import ContentLogin from "./ContentLogin";
import DropDown from "./DropDown";
import ContentReport from "./ContentReport";
import Sidebar from "./Sidebar_test";
import Box_Notif from "./Box_Notif";
import HorizontalBar from "./HorizontalBar";
import DashboardCard from "./DashboardCard";
import DashPie from "./DashPie";

export { NavHome, Hero, Button, Download, Demo, InputText, About, Card, Footer, NavProfile, ContentRegis, DropDown, ContentLogin, ContentReport, Sidebar, Box_Notif, HorizontalBar, DashPie, DashboardCard };
